//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_ZTI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SalesId { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
    }
}
